SRCS	:= Ice.cpp AMateria.cpp main.cpp Cure.cpp Character.cpp MateriaSource.cpp
HEADERS	:= Ice.hpp AMateria.hpp Cure.hpp ICharacter.hpp Character.hpp IMateriaSource.hpp MateriaSource.hpp
TARGET	:= interface

include ../../template.Makefile
