SRCS		:= ClapTrap.cpp ScavTrap.cpp FragTrap.cpp DiamondTrap.cpp main.cpp
HEADERS		:= ClapTrap.hpp ScavTrap.hpp FragTrap.hpp DiamondTrap.hpp
TARGET		:= diamondtrap

include ../../template.Makefile

CPP_FLAGS	+= -Wshadow
