#include <iostream>
#include <cctype>
#include <stdexcept>
#include <fstream>

#include "Contact.h"
#include "PhoneBook.h"
#include "CommandInfo.h"

using std::string;
using std::out_of_range;
using std::left; using std::setw;
using std::istream; using std::flush; using std::endl; using std::cin; using std::cout; using std::cerr;
using std::ofstream; using std::ifstream;

static CommandInfo infos[] = {
	{ "HELP", "Display this help menu", &commandHelp },
	{ "ADD", "Add a contact to the phonebook", &commandAdd },
	{ "SEARCH", "List registered contacts and print informations about a particular one", &commandSearch },
	{ "REMOVE", "Remove a contact at a given index", commandRemove },
	{ "SAVE", "Save the currently stored contacts into the specified file, that will be loadable by the phonebook.", commandSave },
	{ "LOAD", "Load a saved list of contacts from a file. This file should have been generated by the SAVE command.", commandLoad },
	{ "EXIT", "Close the phone book program", commandExit }
};

static bool promptContactIndex(PhoneBook &pb, PhoneBook::size_type &contactIndex)
{
	if (pb.size() == 0) {
		cout << "Can't select: phone book is empty" << endl;
	} else {
		string line;
		cout << "Contact ID (0-" << pb.size() - 1 << ")> ";
		if (getline(cin, line) && line.size() == 1 && isdigit(line[0])) {
			contactIndex = line[0] - 48;
			return true;
		}
	}
	return false;
}

static istream	&promptLine(std::string const &promptContent, std::string &line)
{
	if (cin) {
		cout << promptContent;
		getline(cin, line);
	}
	return cin;
}

inline void	commandExit(PhoneBook &pb)
{
	// simulate EOF
	(void)pb;
	cin.setstate(cin.eofbit);
}

void	commandHelp(PhoneBook &pb)
{
	(void)pb;

	for (size_t i = 0; i != sizeof (infos) / sizeof (*infos); ++i) {
		cout << left << setw(10) << infos[i].label << "" << infos[i].usage << "\n";
	}
	cout << flush;
}

void	commandSave(PhoneBook &pb)
{
	 string filepath;

	 cout << "file path> ";
	 if (getline(cin, filepath)) {
		ofstream ofs(filepath);
		if (ofs) {
			for (PhoneBook::size_type i = 0; i != pb.size(); ++i) {
				Contact const &cp = *pb.getContact(i);
				ofs << cp.getFirstName() << "\n" << cp.getLastName() << "\n"
					<< cp.getNickname() << "\n" << cp.getPhone() << "\n" << cp.getDarkestSecret() << "\n---" << endl;
			}
			cout << "Saved phonebook data in " << filepath << endl;
		} else {
			cerr << "\033[1;31mError\033[0m: could not open file \"" << filepath << "\"" << endl;
		}
	 } else {
		 cerr << "\033[1;31mError\033[0m: Could not read file path" << endl; 
	 }
}

void	commandLoad(PhoneBook &pb)
{
	 string filepath;

	 cout << "file path> ";
	 if (getline(cin, filepath)) {
		ifstream ifs(filepath);
		if (ifs) {
			while (ifs) {
				string firstName, lastName, nickname, phone, darkestSecret;

				getline(ifs, firstName);
				getline(ifs, lastName);
				getline(ifs, nickname);
				getline(ifs, phone);
				getline(ifs, darkestSecret);
				if (ifs) {
					Contact c(firstName, lastName, nickname, phone, darkestSecret);
					pb.addContact(c);
	
					string line;
					if (getline(ifs, line) && line != "---") {
						cerr << "\033[1;31mError\033[0m: could not find delimiter, LOAD is uncomplete." << endl;
						break;
					}
				}
			}
			cout << "Loaded phone data data from " << filepath << endl;
		} else {
			cerr << "\033[1;31mError\033[0m: could not open file \"" << filepath << "\"" << endl;
		}
	 } else {
		 cerr << "\033[1;31mError\033[0m: Could not read file path" << endl; 
	 }
}

void	commandAdd(PhoneBook &pb)
{
	std::string firstName, lastName, nickname, phone, darkestSecret;

	promptLine("firstName> ", firstName);
	promptLine("lastName> ", lastName);
	promptLine("nickname> ", nickname);
	promptLine("phone> ", phone);
	promptLine("darkestSecret> ", darkestSecret);

	Contact contact(firstName, lastName, nickname, phone, darkestSecret);
	pb.addContact(contact);
	cout << "Added " << firstName << " " << lastName << " to the phone book" << endl;
}

void	commandSearch(PhoneBook &pb)
{
	pb.list();
	PhoneBook::size_type contactId;

	if (promptContactIndex(pb, contactId)) {
		try {
			cout << *pb.getContact(contactId) << endl;
		} catch(out_of_range err) {
			cerr << err.what() << endl;
		}
	}
}

void	commandRemove(PhoneBook &pb)
{
	PhoneBook::size_type contactId;

	if (promptContactIndex(pb, contactId)) {
		try {
			pb.removeContact(contactId);
			cout << "Contact removed successfully" << endl;
		} catch(out_of_range err) {
			cerr << err.what() << endl;
		}
	}
}

int main(void)
{
	PhoneBook pb;
	string cmd;

	while (promptLine("\033[0;34mPhoneBook\033[0m> ", cmd)) {
		bool found = false;
		for (size_t i = 0; i != sizeof (infos) / sizeof(*infos); ++i) {
			if (infos[i].label == cmd) {
				infos[i].handler(pb);
				found = true;
				break ;
			}
		}
		if (!found) {
			cerr << "\033[1;31mError\033[0m: Unknown command \"" << cmd << "\". Type HELP for help." << endl;
		}
	}

	cout << "Bye!" << endl;
	
	return 0;
}
